---
title       : Retirement Scenarios
subtitle    : 
author      : Lin Crampton 
job         : Coursera Student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Simulating a Retirement Scenario

Retirement planners create beautiful presentations with authoratative graphs that predict future values of financial assets.  For example, given a lump sum pension payout of $2.5 million, a ROI of 7% (conservatively, they say), augmented by $3000 monthly social security payments, and a need to withdraw $500 per month for living expenses, an advisor could present you with a graph displaying one or two senarios with clear trajectories, with an explaination why this represents your financial future.  

--- 

## Uncertainty is Reality

* In reality, the future is much harder to predict.  If the person sitting across from you showing you these charts were so clearly able to predict future values of assets, they probably would not need to be sitting across from you trying to convince you to give them a percentage of your assets.  

* If you add to the graph uncertainty in inflation and uncertainty in investment returns, then you present a very different picture -- a range of possible scenarios, dependent on the uncertainty in future conditions.  Using the numbers from slide 1 (capital=2.5 million, ROI=7%, etc.), there could be a multitude of financial outcomes -- due to unexpected fluctuations in interest rates, inflation, etc.  For example, at age 88 in this graphic, the retiree is either $200,000 in debt, or has assets of $2 million, or somewhere in between ... not exactly the scenario presented by a single line graph.

--- 

```{r echo=FALSE, results = 'asis'}
#initial conditions
startCapital = 250000; monthlyWithdrawals = 500; numSims=50; monthsObserving=360
# make an age vector, starting with age now
ageNow = 59; ageSeq = seq(from=ageNow*12, by=1, length.out=monthsObserving); ageVecYears = matrix(ageSeq/12)
#monthly returns=7%, inflation=7%
monthlyReturnMean =  0.07/ 12; monthlyStdDev = 0.03 / sqrt(12)
investReturnsMatrix = matrix(0, monthsObserving, numSims); investReturnsMatrix[] = rnorm(monthsObserving * numSims, mean = monthlyReturnMean, sd = monthlyStdDev)
monthlyInflation = 0.07/12; inflationMatrix = matrix(0, monthsObserving, numSims)
inflationMatrix[] = rnorm(monthsObserving * numSims, mean = monthlyInflation, sd = monthlyInflationStdDev)
capitalMatrix = matrix(startCapital, monthsObserving, numSims)
# create matix of observations of dwindling capital
for (j in 1:(monthsObserving-1)) {
	capitalMatrix[j + 1, ] = ( capitalMatrix[j, ] * (1 + investReturnsMatrix[j, ] - inflationMatrix[j, ]) )  - ( monthlyWithdrawals * ( 1 + inflationMatrix[j, ])) } 
capitalMatrix = capitalMatrix / 100000
# prep for plotting
Retirement=cbind(ageVecYears,capitalMatrix); retireMultiLineDF = data.frame(Retirement)
# gVisLineChart
require('googleVis')
retireMultiLine = gvisLineChart(retireMultiLineDF, options=list( title='Projected Retirement Assets', titleTextStyle="{fontSize:16}", legend="none", legend.position="none", linewidth=0.5, vAxis='{title: "Millions (US$)"}', width=1000, height=500, hAxis='{title: "Age (years)"}')) 
print(retireMultiLine)
```

## The app, time2retire

* Produces a graphic illustrating a variety of retirement scenarios
* Enables user to customize to reflect their financial situation
* Run at: http://lincrampton.shinyapps.io/time2retire/
* Source: https://github.com/lincrampton/time2retire


---

## Disclaimers


**I am not a financial planning expert, nor do I have knowledge or expertise in that area.  Do not make financial decisions based on the graphical display generated by this app.**

I cannot take credit for all of the code that went into this project.  Pierre Chretien create original financial simulation code, Michael Kapler modified to include updates and enhancements, and I modified to generate retirement scenarios.

*** =pnotes
This is a slide note.
